import { BookOpen, Layers3, Plus, Save, Video, CheckCircle2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AdminShell } from "@/components/admin/admin-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
const db=supabase as any;
type Program={id:string;name:string;description:string|null;sort_order:number;is_active:boolean};
type Course={id:string;program_id:string;title:string;description:string|null;sort_order:number;is_active:boolean};
type Module={id:string;course_id:string;title:string;description:string|null;sort_order:number;is_active:boolean};
type Lesson={id:string;module_id:string;title:string;sort_order:number;is_active:boolean;video_url:string|null;duration_minutes:number|null};
type Assignment={id:string;module_id:string;title:string;description:string|null;instructions:string|null;sort_order:number;is_required:boolean;is_active:boolean};
type Submission={id:string;assignment_id:string;student_id:string;submission_text:string|null;submission_url:string|null;status:string;feedback:string|null;score:number|null;submitted_at:string};

export function L3CourseAdminPage(){
 const [programs,setPrograms]=useState<Program[]>([]),[courses,setCourses]=useState<Course[]>([]),[modules,setModules]=useState<Module[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]);
 const [programId,setProgramId]=useState(""),[courseId,setCourseId]=useState(""),[moduleId,setModuleId]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState<string|null>(null);
 const [pf,setPf]=useState({name:"",description:"",sort:"1"}),[cf,setCf]=useState({title:"",description:"",sort:"1"}),[mf,setMf]=useState({title:"",description:"",sort:"1"}),[lf,setLf]=useState({title:"",description:"",video:"",resource:"",duration:"",sort:"1"}),[af,setAf]=useState({title:"",description:"",instructions:"",sort:"1"});
 useEffect(()=>{void load()},[]);
 const visibleCourses=useMemo(()=>courses.filter(x=>x.program_id===programId),[courses,programId]),visibleModules=useMemo(()=>modules.filter(x=>x.course_id===courseId),[modules,courseId]),visibleLessons=useMemo(()=>lessons.filter(x=>x.module_id===moduleId),[lessons,moduleId]),visibleAssignments=useMemo(()=>assignments.filter(x=>x.module_id===moduleId),[assignments,moduleId]);
 async function load(){
  const [p,c,m,l,a,s]=await Promise.all([db.from("l3_programs").select("*").order("sort_order"),db.from("l3_courses").select("*").order("sort_order"),db.from("l3_course_modules").select("*").order("sort_order"),db.from("l3_course_lessons").select("*").order("sort_order"),db.from("l3_assignments").select("*").order("sort_order"),db.from("l3_assignment_submissions").select("*").order("updated_at",{ascending:false})]);
  if(p.error||c.error||m.error||l.error||a.error||s.error){setError("Some L3 administration data could not be loaded.");return}
  setPrograms(p.data??[]);setCourses(c.data??[]);setModules(m.data??[]);setLessons(l.data??[]);setAssignments(a.data??[]);setSubmissions(s.data??[]);
  if(!programId&&p.data?.[0])setProgramId(p.data[0].id);if(!courseId&&c.data?.[0])setCourseId(c.data[0].id);if(!moduleId&&m.data?.[0])setModuleId(m.data[0].id);
 }
 async function insert(table:string,data:any,key:string){setBusy(key);setError(null);const u=(await supabase.auth.getUser()).data.user;const r=await db.from(table).insert({...data,created_by:["l3_programs","l3_courses","l3_assignments"].includes(table)?u?.id??null:undefined}).select("*").single();if(r.error)setError(r.error.message);else await load();setBusy("")}
 async function toggle(table:string,id:string,value:boolean){setBusy(id);const r=await db.from(table).update({is_active:value}).eq("id",id);if(r.error)setError(r.error.message);else await load();setBusy("")}
 async function review(s:Submission,status:string){setBusy(s.id);const u=(await supabase.auth.getUser()).data.user;const r=await db.from("l3_assignment_submissions").update({status,reviewer_id:u?.id??null,reviewed_at:new Date().toISOString()}).eq("id",s.id);if(r.error)setError(r.error.message);else await load();setBusy("")}
 return <AdminShell title="L3 Career Track" subtitle="Build Program → Course → Module → Lesson → Assignment and review Leader submissions centrally.">
  <div className="space-y-6">{error&&<Card className="border-destructive/30 bg-destructive/5"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
   <Card className="border-primary/20 bg-primary/[0.03]"><CardContent className="p-6"><div className="grid gap-4 md:grid-cols-5"><div><p className="text-xs uppercase text-muted-foreground">Programs</p><p className="text-2xl font-bold">{programs.length}</p></div><div><p className="text-xs uppercase text-muted-foreground">Courses</p><p className="text-2xl font-bold">{courses.length}</p></div><div><p className="text-xs uppercase text-muted-foreground">Modules</p><p className="text-2xl font-bold">{modules.length}</p></div><div><p className="text-xs uppercase text-muted-foreground">Assignments</p><p className="text-2xl font-bold">{assignments.length}</p></div><div><p className="text-xs uppercase text-muted-foreground">Submissions</p><p className="text-2xl font-bold">{submissions.length}</p></div></div></CardContent></Card>
   <section className="grid gap-4 lg:grid-cols-2">
    <Card><CardHeader><CardTitle>Create L3 program</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Program name" value={pf.name} onChange={e=>setPf({...pf,name:e.target.value})}/><Textarea placeholder="Description" value={pf.description} onChange={e=>setPf({...pf,description:e.target.value})}/><Input type="number" placeholder="Sort order" value={pf.sort} onChange={e=>setPf({...pf,sort:e.target.value})}/><Button disabled={!pf.name.trim()||busy==="program"} onClick={()=>void insert("l3_programs",{name:pf.name.trim(),description:pf.description.trim()||null,sort_order:Number(pf.sort)||1,is_active:false},"program")}><Plus/>Add program</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>Programs</CardTitle></CardHeader><CardContent className="space-y-3">{programs.map(p=><div key={p.id} className="rounded-xl border p-4 flex justify-between gap-3"><div><p className="font-semibold">{p.name}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setProgramId(p.id)}>Manage</Button><Button size="sm" variant={p.is_active?"secondary":"default"} onClick={()=>void toggle("l3_programs",p.id,!p.is_active)}>{p.is_active?"Published":"Publish"}</Button></div></div>)}</CardContent></Card>
   </section>
   <section className="grid gap-4 lg:grid-cols-2">
    <Card><CardHeader><CardTitle>Create course</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Select program</option>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Input placeholder="Course title" value={cf.title} onChange={e=>setCf({...cf,title:e.target.value})}/><Textarea placeholder="Description" value={cf.description} onChange={e=>setCf({...cf,description:e.target.value})}/><Input type="number" value={cf.sort} onChange={e=>setCf({...cf,sort:e.target.value})}/><Button disabled={!programId||!cf.title.trim()} onClick={()=>void insert("l3_courses",{program_id:programId,title:cf.title.trim(),description:cf.description.trim()||null,sort_order:Number(cf.sort)||1,is_active:false},"course")}><Plus/>Add course</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>Courses</CardTitle></CardHeader><CardContent className="space-y-3">{visibleCourses.map(c=><div key={c.id} className="rounded-xl border p-4 flex justify-between gap-3"><p className="font-semibold">{c.title}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setCourseId(c.id)}>Manage</Button><Button size="sm" variant={c.is_active?"secondary":"default"} onClick={()=>void toggle("l3_courses",c.id,!c.is_active)}>{c.is_active?"Published":"Publish"}</Button></div></div>)}</CardContent></Card>
   </section>
   <section className="grid gap-4 lg:grid-cols-2">
    <Card><CardHeader><CardTitle>Create module</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Select course</option>{visibleCourses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><Input placeholder="Module title" value={mf.title} onChange={e=>setMf({...mf,title:e.target.value})}/><Textarea placeholder="Description" value={mf.description} onChange={e=>setMf({...mf,description:e.target.value})}/><Input type="number" value={mf.sort} onChange={e=>setMf({...mf,sort:e.target.value})}/><Button disabled={!courseId||!mf.title.trim()} onClick={()=>void insert("l3_course_modules",{course_id:courseId,title:mf.title.trim(),description:mf.description.trim()||null,sort_order:Number(mf.sort)||1,is_active:false},"module")}><Plus/>Add module</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>Modules</CardTitle></CardHeader><CardContent className="space-y-3">{visibleModules.map(m=><div key={m.id} className="rounded-xl border p-4 flex justify-between gap-3"><p className="font-semibold">{m.title}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setModuleId(m.id)}>Manage</Button><Button size="sm" variant={m.is_active?"secondary":"default"} onClick={()=>void toggle("l3_course_modules",m.id,!m.is_active)}>{m.is_active?"Live":"Activate"}</Button></div></div>)}</CardContent></Card>
   </section>
   <section className="grid gap-4 lg:grid-cols-2">
    <Card><CardHeader><CardTitle>Create lesson</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={moduleId} onChange={e=>setModuleId(e.target.value)}><option value="">Select module</option>{visibleModules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select><Input placeholder="Lesson title" value={lf.title} onChange={e=>setLf({...lf,title:e.target.value})}/><Textarea placeholder="Description" value={lf.description} onChange={e=>setLf({...lf,description:e.target.value})}/><Input placeholder="Video URL" value={lf.video} onChange={e=>setLf({...lf,video:e.target.value})}/><Input placeholder="Resource URL" value={lf.resource} onChange={e=>setLf({...lf,resource:e.target.value})}/><div className="grid grid-cols-2 gap-3"><Input type="number" placeholder="Minutes" value={lf.duration} onChange={e=>setLf({...lf,duration:e.target.value})}/><Input type="number" value={lf.sort} onChange={e=>setLf({...lf,sort:e.target.value})}/></div><Button disabled={!moduleId||!lf.title.trim()} onClick={()=>void insert("l3_course_lessons",{module_id:moduleId,title:lf.title.trim(),description:lf.description.trim()||null,lesson_type:"video",video_url:lf.video.trim()||null,resource_url:lf.resource.trim()||null,duration_minutes:lf.duration?Number(lf.duration):null,sort_order:Number(lf.sort)||1,is_active:false},"lesson")}><Save/>Add lesson</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>Lessons</CardTitle></CardHeader><CardContent className="space-y-3">{visibleLessons.map(l=><div key={l.id} className="rounded-xl border p-4 flex justify-between gap-3"><p className="font-semibold">{l.title}</p><Button size="sm" variant={l.is_active?"secondary":"default"} onClick={()=>void toggle("l3_course_lessons",l.id,!l.is_active)}>{l.is_active?"Published":"Publish"}</Button></div>)}</CardContent></Card>
   </section>
   <section className="grid gap-4 lg:grid-cols-2">
    <Card><CardHeader><CardTitle>Create assignment</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={moduleId} onChange={e=>setModuleId(e.target.value)}><option value="">Select module</option>{visibleModules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select><Input placeholder="Assignment title" value={af.title} onChange={e=>setAf({...af,title:e.target.value})}/><Textarea placeholder="Short description" value={af.description} onChange={e=>setAf({...af,description:e.target.value})}/><Textarea placeholder="Assignment instructions" value={af.instructions} onChange={e=>setAf({...af,instructions:e.target.value})}/><Input type="number" value={af.sort} onChange={e=>setAf({...af,sort:e.target.value})}/><Button disabled={!moduleId||!af.title.trim()} onClick={()=>void insert("l3_assignments",{module_id:moduleId,title:af.title.trim(),description:af.description.trim()||null,instructions:af.instructions.trim()||null,sort_order:Number(af.sort)||1,is_required:true,is_active:false},"assignment")}><Plus/>Add assignment</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>Assignments</CardTitle></CardHeader><CardContent className="space-y-3">{visibleAssignments.map(a=><div key={a.id} className="rounded-xl border p-4 flex justify-between gap-3"><div><p className="font-semibold">{a.title}</p><p className="text-xs text-muted-foreground">Required · order {a.sort_order}</p></div><Button size="sm" variant={a.is_active?"secondary":"default"} onClick={()=>void toggle("l3_assignments",a.id,!a.is_active)}>{a.is_active?"Published":"Publish"}</Button></div>)}</CardContent></Card>
   </section>
   <Card><CardHeader><CardTitle>Central L3 assignment submissions</CardTitle><p className="text-sm text-muted-foreground">All Leader submissions in one admin review queue.</p></CardHeader><CardContent className="space-y-3">{submissions.map(s=>{const a=assignments.find(x=>x.id===s.assignment_id);return <div key={s.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{a?.title??"Assignment"}</p><p className="text-xs text-muted-foreground">Leader: {s.student_id} · {new Date(s.submitted_at).toLocaleString()}</p></div><Badge variant={s.status==="reviewed"?"default":"outline"}>{s.status}</Badge></div>{s.submission_text&&<p className="mt-3 whitespace-pre-wrap text-sm leading-6">{s.submission_text}</p>}{s.submission_url&&<a className="mt-2 block break-all text-sm text-primary" href={s.submission_url} target="_blank" rel="noreferrer">{s.submission_url}</a>}{s.feedback&&<p className="mt-2 text-sm text-muted-foreground">Feedback: {s.feedback}</p>}<div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy===s.id} onClick={()=>void review(s,"under_review")}><Save/>Under review</Button><Button size="sm" disabled={busy===s.id} onClick={()=>void review(s,"reviewed")}><CheckCircle2/>Reviewed</Button><Button size="sm" variant="outline" disabled={busy===s.id} onClick={()=>void review(s,"needs_revision")}>Needs revision</Button></div></div>})}{!submissions.length&&<p className="text-sm text-muted-foreground">No Leader submissions yet.</p>}</CardContent></Card>
  </div>
 </AdminShell>;
}
