/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterclassRouteImport } from './routes/masterclass'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardAssessmentRouteImport } from './routes/_authenticated/dashboard/assessment'
import { Route as AuthenticatedDashboardL1KnowledgeCheckRouteImport } from './routes/_authenticated/dashboard/l1-knowledge-check'
import { Route as AuthenticatedDashboardL1LearningRouteImport } from './routes/_authenticated/dashboard/l1-learning'
import { Route as AuthenticatedDashboardInterviewQuestionsRouteImport } from './routes/_authenticated/dashboard/interview-questions'
import { Route as AuthenticatedDashboardFoundationRouteImport } from './routes/_authenticated/dashboard/foundation'
import { Route as AuthenticatedDashboardJobsRouteImport } from './routes/_authenticated/dashboard/jobs'
import { Route as AuthenticatedDashboardApplicationsRouteImport } from './routes/_authenticated/dashboard/applications'
import { Route as AuthenticatedDashboardCareerOsRouteImport } from './routes/_authenticated/dashboard/career-os'
import { Route as AuthenticatedAdminMasterclassRouteImport } from './routes/_authenticated/admin/masterclass'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminFoundationRouteImport } from './routes/_authenticated/admin/foundation'
import { Route as AuthenticatedAdminL1LearningRouteImport } from './routes/_authenticated/admin/l1-learning'
import { Route as AuthenticatedAdminInterviewQuestionsRouteImport } from './routes/_authenticated/admin/interview-questions'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin/applications'
import { Route as AuthenticatedAdminAssessmentsRouteImport } from './routes/_authenticated/admin/assessments'
import { Route as AuthenticatedAdminCareerOsRouteImport } from './routes/_authenticated/admin/career-os'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterclassRoute = MasterclassRouteImport.update({
  id: '/masterclass',
  path: '/masterclass',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardProfileRoute = AuthenticatedDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardAssessmentRoute = AuthenticatedDashboardAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardL1KnowledgeCheckRoute = AuthenticatedDashboardL1KnowledgeCheckRouteImport.update({
  id: '/l1-knowledge-check',
  path: '/l1-knowledge-check',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardL1LearningRoute = AuthenticatedDashboardL1LearningRouteImport.update({
  id: '/l1-learning',
  path: '/l1-learning',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardInterviewQuestionsRoute = AuthenticatedDashboardInterviewQuestionsRouteImport.update({
  id: '/interview-questions',
  path: '/interview-questions',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardFoundationRoute = AuthenticatedDashboardFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardJobsRoute = AuthenticatedDashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardApplicationsRoute = AuthenticatedDashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedDashboardCareerOsRoute = AuthenticatedDashboardCareerOsRouteImport.update({
  id: '/career-os',
  path: '/career-os',
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any)
const AuthenticatedAdminMasterclassRoute =
  AuthenticatedAdminMasterclassRouteImport.update({
    id: '/masterclass',
    path: '/masterclass',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminL1LearningRoute = AuthenticatedAdminL1LearningRouteImport.update({
  id: '/l1-learning',
  path: '/l1-learning',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInterviewQuestionsRoute = AuthenticatedAdminInterviewQuestionsRouteImport.update({
  id: '/interview-questions',
  path: '/interview-questions',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFoundationRoute =
  AuthenticatedAdminFoundationRouteImport.update({
    id: '/foundation',
    path: '/foundation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApplicationsRoute = AuthenticatedAdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAssessmentsRoute = AuthenticatedAdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCareerOsRoute = AuthenticatedAdminCareerOsRouteImport.update({
  id: '/career-os',
  path: '/career-os',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/framework': typeof FrameworkRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/masterclass': typeof MasterclassRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/assessment': typeof AuthenticatedDashboardAssessmentRoute
  '/dashboard/l1-learning': typeof AuthenticatedDashboardL1LearningRoute
  '/dashboard/interview-questions': typeof AuthenticatedDashboardInterviewQuestionsRoute
  '/dashboard/foundation': typeof AuthenticatedDashboardFoundationRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard/career-os': typeof AuthenticatedDashboardCareerOsRoute
  '/admin/masterclass': typeof AuthenticatedAdminMasterclassRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/foundation': typeof AuthenticatedAdminFoundationRoute
  '/admin/l1-learning': typeof AuthenticatedAdminL1LearningRoute
  '/admin/interview-questions': typeof AuthenticatedAdminInterviewQuestionsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/career-os': typeof AuthenticatedAdminCareerOsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/framework': typeof FrameworkRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/masterclass': typeof MasterclassRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/l1-learning': typeof AuthenticatedDashboardL1LearningRoute
  '/dashboard/foundation': typeof AuthenticatedDashboardFoundationRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/admin/masterclass': typeof AuthenticatedAdminMasterclassRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/framework': typeof FrameworkRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/masterclass': typeof MasterclassRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/l1-learning': typeof AuthenticatedDashboardL1LearningRoute
  '/_authenticated/dashboard/interview-questions': typeof AuthenticatedDashboardInterviewQuestionsRoute
  '/_authenticated/admin/masterclass': typeof AuthenticatedAdminMasterclassRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/foundation': typeof AuthenticatedAdminFoundationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/framework'
    | '/get-started'
    | '/login'
    | '/masterclass'
    | '/privacy'
    | '/programs'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/admin'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/assessment'
    | '/dashboard/l1-knowledge-check'
    | '/dashboard/l1-learning'
    | '/dashboard/interview-questions'
    | '/dashboard/foundation'
    | '/admin/masterclass'
    | '/admin/students'
    | '/admin/foundation'
    | '/admin/l1-learning'
    | '/admin/interview-questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/framework'
    | '/get-started'
    | '/login'
    | '/masterclass'
    | '/privacy'
    | '/programs'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/admin'
    | '/dashboard'
    | '/dashboard/profile'
    | '/admin/masterclass'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/framework'
    | '/get-started'
    | '/login'
    | '/masterclass'
    | '/privacy'
    | '/programs'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/assessment'
    | '/_authenticated/admin/masterclass'
    | '/_authenticated/admin/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FrameworkRoute: typeof FrameworkRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  MasterclassRoute: typeof MasterclassRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterclass': {
      id: '/masterclass'
      path: '/masterclass'
      fullPath: '/masterclass'
      preLoaderRoute: typeof MasterclassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assessment': {
      id: '/_authenticated/dashboard/assessment'
      path: '/assessment'
      fullPath: '/dashboard/assessment'
      preLoaderRoute: typeof AuthenticatedDashboardAssessmentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/masterclass': {
      id: '/_authenticated/admin/masterclass'
      path: '/masterclass'
      fullPath: '/admin/masterclass'
      preLoaderRoute: typeof AuthenticatedAdminMasterclassRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/jobs': {
      id: '/_authenticated/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof AuthenticatedDashboardJobsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/career-os': {
      id: '/_authenticated/dashboard/career-os'
      path: '/career-os'
      fullPath: '/dashboard/career-os'
      preLoaderRoute: typeof AuthenticatedDashboardCareerOsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/applications': {
      id: '/_authenticated/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/career-os': {
      id: '/_authenticated/admin/career-os'
      path: '/career-os'
      fullPath: '/admin/career-os'
      preLoaderRoute: typeof AuthenticatedAdminCareerOsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assessments': {
      id: '/_authenticated/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardAssessmentRoute: typeof AuthenticatedDashboardAssessmentRoute
  AuthenticatedDashboardL1KnowledgeCheckRoute: typeof AuthenticatedDashboardL1KnowledgeCheckRoute
  AuthenticatedDashboardL1LearningRoute: typeof AuthenticatedDashboardL1LearningRoute
  AuthenticatedDashboardInterviewQuestionsRoute: typeof AuthenticatedDashboardInterviewQuestionsRoute
  AuthenticatedDashboardFoundationRoute: typeof AuthenticatedDashboardFoundationRoute
  AuthenticatedDashboardJobsRoute: typeof AuthenticatedDashboardJobsRoute
  AuthenticatedDashboardApplicationsRoute: typeof AuthenticatedDashboardApplicationsRoute
  AuthenticatedDashboardCareerOsRoute: typeof AuthenticatedDashboardCareerOsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren = {
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardAssessmentRoute: AuthenticatedDashboardAssessmentRoute,
  AuthenticatedDashboardL1KnowledgeCheckRoute: AuthenticatedDashboardL1KnowledgeCheckRoute,
  AuthenticatedDashboardL1LearningRoute: AuthenticatedDashboardL1LearningRoute,
  AuthenticatedDashboardInterviewQuestionsRoute: AuthenticatedDashboardInterviewQuestionsRoute,
  AuthenticatedDashboardFoundationRoute: AuthenticatedDashboardFoundationRoute,
  AuthenticatedDashboardJobsRoute: AuthenticatedDashboardJobsRoute,
  AuthenticatedDashboardApplicationsRoute: AuthenticatedDashboardApplicationsRoute,
  AuthenticatedDashboardCareerOsRoute: AuthenticatedDashboardCareerOsRoute,
}

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(AuthenticatedDashboardRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMasterclassRoute: typeof AuthenticatedAdminMasterclassRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminFoundationRoute: typeof AuthenticatedAdminFoundationRoute
  AuthenticatedAdminL1LearningRoute: typeof AuthenticatedAdminL1LearningRoute
  AuthenticatedAdminInterviewQuestionsRoute: typeof AuthenticatedAdminInterviewQuestionsRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAssessmentsRoute: typeof AuthenticatedAdminAssessmentsRoute
  AuthenticatedAdminCareerOsRoute: typeof AuthenticatedAdminCareerOsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMasterclassRoute: AuthenticatedAdminMasterclassRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminFoundationRoute: AuthenticatedAdminFoundationRoute,
  AuthenticatedAdminL1LearningRoute: AuthenticatedAdminL1LearningRoute,
  AuthenticatedAdminInterviewQuestionsRoute: AuthenticatedAdminInterviewQuestionsRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAssessmentsRoute: AuthenticatedAdminAssessmentsRoute,
  AuthenticatedAdminCareerOsRoute: AuthenticatedAdminCareerOsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FrameworkRoute: FrameworkRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  MasterclassRoute: MasterclassRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
