/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterclassRouteImport } from './routes/masterclass'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthenticatedAdminAdmin360RouteImport } from './routes/_authenticated/admin/admin-360'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin/applications'
import { Route as AuthenticatedAdminAssessmentsRouteImport } from './routes/_authenticated/admin/assessments'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin/blog'
import { Route as AuthenticatedAdminCareerOsRouteImport } from './routes/_authenticated/admin/career-os'
import { Route as AuthenticatedAdminFoundationRouteImport } from './routes/_authenticated/admin/foundation'
import { Route as AuthenticatedAdminInterviewQuestionsRouteImport } from './routes/_authenticated/admin/interview-questions'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminL1LearningRouteImport } from './routes/_authenticated/admin/l1-learning'
import { Route as AuthenticatedAdminMasterclassRouteImport } from './routes/_authenticated/admin/masterclass'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedDashboardApplicationsRouteImport } from './routes/_authenticated/dashboard/applications'
import { Route as AuthenticatedDashboardAssessmentRouteImport } from './routes/_authenticated/dashboard/assessment'
import { Route as AuthenticatedDashboardCareerOsRouteImport } from './routes/_authenticated/dashboard/career-os'
import { Route as AuthenticatedDashboardFoundationRouteImport } from './routes/_authenticated/dashboard/foundation'
import { Route as AuthenticatedDashboardInterviewQuestionsRouteImport } from './routes/_authenticated/dashboard/interview-questions'
import { Route as AuthenticatedDashboardJobsRouteImport } from './routes/_authenticated/dashboard/jobs'
import { Route as AuthenticatedDashboardL1KnowledgeCheckRouteImport } from './routes/_authenticated/dashboard/l1-knowledge-check'
import { Route as AuthenticatedDashboardL2KnowledgeCheckRouteImport } from './routes/_authenticated/dashboard/l2-knowledge-check'
import { Route as AuthenticatedDashboardL1LearningRouteImport } from './routes/_authenticated/dashboard/l1-learning'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterclassRoute = MasterclassRouteImport.update({
  id: '/masterclass',
  path: '/masterclass',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminAdmin360Route =
  AuthenticatedAdminAdmin360RouteImport.update({
    id: '/admin-360',
    path: '/admin-360',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssessmentsRoute =
  AuthenticatedAdminAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCareerOsRoute =
  AuthenticatedAdminCareerOsRouteImport.update({
    id: '/career-os',
    path: '/career-os',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFoundationRoute =
  AuthenticatedAdminFoundationRouteImport.update({
    id: '/foundation',
    path: '/foundation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInterviewQuestionsRoute =
  AuthenticatedAdminInterviewQuestionsRouteImport.update({
    id: '/interview-questions',
    path: '/interview-questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminL1LearningRoute =
  AuthenticatedAdminL1LearningRouteImport.update({
    id: '/l1-learning',
    path: '/l1-learning',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMasterclassRoute =
  AuthenticatedAdminMasterclassRouteImport.update({
    id: '/masterclass',
    path: '/masterclass',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardApplicationsRoute =
  AuthenticatedDashboardApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssessmentRoute =
  AuthenticatedDashboardAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCareerOsRoute =
  AuthenticatedDashboardCareerOsRouteImport.update({
    id: '/career-os',
    path: '/career-os',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFoundationRoute =
  AuthenticatedDashboardFoundationRouteImport.update({
    id: '/foundation',
    path: '/foundation',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInterviewQuestionsRoute =
  AuthenticatedDashboardInterviewQuestionsRouteImport.update({
    id: '/interview-questions',
    path: '/interview-questions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardJobsRoute =
  AuthenticatedDashboardJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardL1KnowledgeCheckRoute =
  AuthenticatedDashboardL1KnowledgeCheckRouteImport.update({
    id: '/l1-knowledge-check',
    path: '/l1-knowledge-check',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardL2KnowledgeCheckRoute =
  AuthenticatedDashboardL2KnowledgeCheckRouteImport.update({
    id: '/l2-knowledge-check',
    path: '/l2-knowledge-check',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardL1LearningRoute =
  AuthenticatedDashboardL1LearningRouteImport.update({
    id: '/l1-learning',
    path: '/l1-learning',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/framework': typeof FrameworkRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/masterclass': typeof MasterclassRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/admin-360': typeof AuthenticatedAdminAdmin360Route
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/career-os': typeof AuthenticatedAdminCareerOsRoute
  '/admin/foundation': typeof AuthenticatedAdminFoundationRoute
  '/admin/interview-questions': typeof AuthenticatedAdminInterviewQuestionsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/l1-learning': typeof AuthenticatedAdminL1LearningRoute
  '/admin/masterclass': typeof AuthenticatedAdminMasterclassRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard/assessment': typeof AuthenticatedDashboardAssessmentRoute
  '/dashboard/career-os': typeof AuthenticatedDashboardCareerOsRoute
  '/dashboard/foundation': typeof AuthenticatedDashboardFoundationRoute
  '/dashboard/interview-questions': typeof AuthenticatedDashboardInterviewQuestionsRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/l1-knowledge-check': typeof AuthenticatedDashboardL1KnowledgeCheckRoute
  '/dashboard/l2-knowledge-check': typeof AuthenticatedDashboardL2KnowledgeCheckRoute
  '/dashboard/l1-learning': typeof AuthenticatedDashboardL1LearningRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/framework': typeof FrameworkRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/masterclass': typeof MasterclassRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/admin-360': typeof AuthenticatedAdminAdmin360Route
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/career-os': typeof AuthenticatedAdminCareerOsRoute
  '/admin/foundation': typeof AuthenticatedAdminFoundationRoute
  '/admin/interview-questions': typeof AuthenticatedAdminInterviewQuestionsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/l1-learning': typeof AuthenticatedAdminL1LearningRoute
  '/admin/masterclass': typeof AuthenticatedAdminMasterclassRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard/assessment': typeof AuthenticatedDashboardAssessmentRoute
  '/dashboard/career-os': typeof AuthenticatedDashboardCareerOsRoute
  '/dashboard/foundation': typeof AuthenticatedDashboardFoundationRoute
  '/dashboard/interview-questions': typeof AuthenticatedDashboardInterviewQuestionsRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/l1-knowledge-check': typeof AuthenticatedDashboardL1KnowledgeCheckRoute
  '/dashboard/l1-learning': typeof AuthenticatedDashboardL1LearningRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/framework': typeof FrameworkRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/masterclass': typeof MasterclassRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/admin/admin-360': typeof AuthenticatedAdminAdmin360Route
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/career-os': typeof AuthenticatedAdminCareerOsRoute
  '/_authenticated/admin/foundation': typeof AuthenticatedAdminFoundationRoute
  '/_authenticated/admin/interview-questions': typeof AuthenticatedAdminInterviewQuestionsRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/l1-learning': typeof AuthenticatedAdminL1LearningRoute
  '/_authenticated/admin/masterclass': typeof AuthenticatedAdminMasterclassRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/_authenticated/dashboard/assessment': typeof AuthenticatedDashboardAssessmentRoute
  '/_authenticated/dashboard/career-os': typeof AuthenticatedDashboardCareerOsRoute
  '/_authenticated/dashboard/foundation': typeof AuthenticatedDashboardFoundationRoute
  '/_authenticated/dashboard/interview-questions': typeof AuthenticatedDashboardInterviewQuestionsRoute
  '/_authenticated/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/_authenticated/dashboard/l1-knowledge-check': typeof AuthenticatedDashboardL1KnowledgeCheckRoute
  '/_authenticated/dashboard/l1-learning': typeof AuthenticatedDashboardL1LearningRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/framework'
    | '/get-started'
    | '/login'
    | '/masterclass'
    | '/privacy'
    | '/programs'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/admin'
    | '/dashboard'
    | '/blog/$slug'
    | '/admin/admin-360'
    | '/admin/applications'
    | '/admin/assessments'
    | '/admin/blog'
    | '/admin/career-os'
    | '/admin/foundation'
    | '/admin/interview-questions'
    | '/admin/jobs'
    | '/admin/l1-learning'
    | '/admin/masterclass'
    | '/admin/payments'
    | '/admin/students'
    | '/dashboard/applications'
    | '/dashboard/assessment'
    | '/dashboard/career-os'
    | '/dashboard/foundation'
    | '/dashboard/interview-questions'
    | '/dashboard/jobs'
    | '/dashboard/l1-knowledge-check'
    | '/dashboard/l1-learning'
    | '/dashboard/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/framework'
    | '/get-started'
    | '/login'
    | '/masterclass'
    | '/privacy'
    | '/programs'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/admin'
    | '/dashboard'
    | '/blog/$slug'
    | '/admin/admin-360'
    | '/admin/applications'
    | '/admin/assessments'
    | '/admin/blog'
    | '/admin/career-os'
    | '/admin/foundation'
    | '/admin/interview-questions'
    | '/admin/jobs'
    | '/admin/l1-learning'
    | '/admin/masterclass'
    | '/admin/payments'
    | '/admin/students'
    | '/dashboard/applications'
    | '/dashboard/assessment'
    | '/dashboard/career-os'
    | '/dashboard/foundation'
    | '/dashboard/interview-questions'
    | '/dashboard/jobs'
    | '/dashboard/l1-knowledge-check'
    | '/dashboard/l1-learning'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/framework'
    | '/get-started'
    | '/login'
    | '/masterclass'
    | '/privacy'
    | '/programs'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/_authenticated/admin/admin-360'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/assessments'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/career-os'
    | '/_authenticated/admin/foundation'
    | '/_authenticated/admin/interview-questions'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/l1-learning'
    | '/_authenticated/admin/masterclass'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/students'
    | '/_authenticated/dashboard/applications'
    | '/_authenticated/dashboard/assessment'
    | '/_authenticated/dashboard/career-os'
    | '/_authenticated/dashboard/foundation'
    | '/_authenticated/dashboard/interview-questions'
    | '/_authenticated/dashboard/jobs'
    | '/_authenticated/dashboard/l1-knowledge-check'
    | '/_authenticated/dashboard/l1-learning'
    | '/_authenticated/dashboard/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FrameworkRoute: typeof FrameworkRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  MasterclassRoute: typeof MasterclassRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterclass': {
      id: '/masterclass'
      path: '/masterclass'
      fullPath: '/masterclass'
      preLoaderRoute: typeof MasterclassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin/admin-360': {
      id: '/_authenticated/admin/admin-360'
      path: '/admin-360'
      fullPath: '/admin/admin-360'
      preLoaderRoute: typeof AuthenticatedAdminAdmin360RouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assessments': {
      id: '/_authenticated/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/career-os': {
      id: '/_authenticated/admin/career-os'
      path: '/career-os'
      fullPath: '/admin/career-os'
      preLoaderRoute: typeof AuthenticatedAdminCareerOsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/foundation': {
      id: '/_authenticated/admin/foundation'
      path: '/foundation'
      fullPath: '/admin/foundation'
      preLoaderRoute: typeof AuthenticatedAdminFoundationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/interview-questions': {
      id: '/_authenticated/admin/interview-questions'
      path: '/interview-questions'
      fullPath: '/admin/interview-questions'
      preLoaderRoute: typeof AuthenticatedAdminInterviewQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/l1-learning': {
      id: '/_authenticated/admin/l1-learning'
      path: '/l1-learning'
      fullPath: '/admin/l1-learning'
      preLoaderRoute: typeof AuthenticatedAdminL1LearningRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/masterclass': {
      id: '/_authenticated/admin/masterclass'
      path: '/masterclass'
      fullPath: '/admin/masterclass'
      preLoaderRoute: typeof AuthenticatedAdminMasterclassRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/applications': {
      id: '/_authenticated/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assessment': {
      id: '/_authenticated/dashboard/assessment'
      path: '/assessment'
      fullPath: '/dashboard/assessment'
      preLoaderRoute: typeof AuthenticatedDashboardAssessmentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/career-os': {
      id: '/_authenticated/dashboard/career-os'
      path: '/career-os'
      fullPath: '/dashboard/career-os'
      preLoaderRoute: typeof AuthenticatedDashboardCareerOsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/foundation': {
      id: '/_authenticated/dashboard/foundation'
      path: '/foundation'
      fullPath: '/dashboard/foundation'
      preLoaderRoute: typeof AuthenticatedDashboardFoundationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/interview-questions': {
      id: '/_authenticated/dashboard/interview-questions'
      path: '/interview-questions'
      fullPath: '/dashboard/interview-questions'
      preLoaderRoute: typeof AuthenticatedDashboardInterviewQuestionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/jobs': {
      id: '/_authenticated/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof AuthenticatedDashboardJobsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/l1-knowledge-check': {
      id: '/_authenticated/dashboard/l1-knowledge-check'
      path: '/l1-knowledge-check'
      fullPath: '/dashboard/l1-knowledge-check'
      preLoaderRoute: typeof AuthenticatedDashboardL1KnowledgeCheckRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/l1-learning': {
      id: '/_authenticated/dashboard/l1-learning'
      path: '/l1-learning'
      fullPath: '/dashboard/l1-learning'
      preLoaderRoute: typeof AuthenticatedDashboardL1LearningRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdmin360Route: typeof AuthenticatedAdminAdmin360Route
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAssessmentsRoute: typeof AuthenticatedAdminAssessmentsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCareerOsRoute: typeof AuthenticatedAdminCareerOsRoute
  AuthenticatedAdminFoundationRoute: typeof AuthenticatedAdminFoundationRoute
  AuthenticatedAdminInterviewQuestionsRoute: typeof AuthenticatedAdminInterviewQuestionsRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminL1LearningRoute: typeof AuthenticatedAdminL1LearningRoute
  AuthenticatedAdminMasterclassRoute: typeof AuthenticatedAdminMasterclassRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdmin360Route: AuthenticatedAdminAdmin360Route,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAssessmentsRoute: AuthenticatedAdminAssessmentsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCareerOsRoute: AuthenticatedAdminCareerOsRoute,
  AuthenticatedAdminFoundationRoute: AuthenticatedAdminFoundationRoute,
  AuthenticatedAdminInterviewQuestionsRoute:
    AuthenticatedAdminInterviewQuestionsRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminL1LearningRoute: AuthenticatedAdminL1LearningRoute,
  AuthenticatedAdminMasterclassRoute: AuthenticatedAdminMasterclassRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardApplicationsRoute: typeof AuthenticatedDashboardApplicationsRoute
  AuthenticatedDashboardAssessmentRoute: typeof AuthenticatedDashboardAssessmentRoute
  AuthenticatedDashboardCareerOsRoute: typeof AuthenticatedDashboardCareerOsRoute
  AuthenticatedDashboardFoundationRoute: typeof AuthenticatedDashboardFoundationRoute
  AuthenticatedDashboardInterviewQuestionsRoute: typeof AuthenticatedDashboardInterviewQuestionsRoute
  AuthenticatedDashboardJobsRoute: typeof AuthenticatedDashboardJobsRoute
  AuthenticatedDashboardL1KnowledgeCheckRoute: typeof AuthenticatedDashboardL1KnowledgeCheckRoute
  AuthenticatedDashboardL2KnowledgeCheckRoute: typeof AuthenticatedDashboardL2KnowledgeCheckRoute
  AuthenticatedDashboardL1LearningRoute: typeof AuthenticatedDashboardL1LearningRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardApplicationsRoute:
      AuthenticatedDashboardApplicationsRoute,
    AuthenticatedDashboardAssessmentRoute:
      AuthenticatedDashboardAssessmentRoute,
    AuthenticatedDashboardCareerOsRoute: AuthenticatedDashboardCareerOsRoute,
    AuthenticatedDashboardFoundationRoute:
      AuthenticatedDashboardFoundationRoute,
    AuthenticatedDashboardInterviewQuestionsRoute:
      AuthenticatedDashboardInterviewQuestionsRoute,
    AuthenticatedDashboardJobsRoute: AuthenticatedDashboardJobsRoute,
    AuthenticatedDashboardL1KnowledgeCheckRoute:
      AuthenticatedDashboardL1KnowledgeCheckRoute,
    AuthenticatedDashboardL2KnowledgeCheckRoute:
      AuthenticatedDashboardL2KnowledgeCheckRoute,
    AuthenticatedDashboardL1LearningRoute:
      AuthenticatedDashboardL1LearningRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FrameworkRoute: FrameworkRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  MasterclassRoute: MasterclassRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
